name: cent_music
description: "CENT Music Streaming Platform - High Performance Edition"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Media & Engine
  youtube_explode_dart: ^2.2.2
  just_audio: ^0.9.42
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  
  # Storage & Caching
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
