name: cent
description: A high-performance, encrypted audio streaming engine.
version: 1.0.0+1
publish_to: 'none'

environment:
  # تعديل الـ SDK ليدعم الكود القديم والجديد ويحل مشكلة Null Safety
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  youtube_explode_dart: ^2.2.2
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  crypto: ^3.0.3
  # تحديث النسخة لحل خطأ "version solving failed" الذي ظهر في الصور
  fft: ^0.5.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Michroma
      fonts:
        - asset: fonts/Michroma-Regular.ttf
        
